type Continent {
	code: ID!
	name: String!
	countries: [Country!]!
}

query ListCountries {
	countries {
		code
		name
		emoji
		capital
	}
}

query CountryByCode( $code: ID! ) {
	country( code: $code ) {
		code
		name
		native
		capital
		emoji
		currency
		phone
		continent {
			code
			name
		}
		languages {
			code
			name
		}
	}
}
